receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  prometheus/collector:
    config:
      scrape_configs:
        - job_name: "server1"
          static_configs:
            - targets: ["server1:8084"]
          metrics_path: "/actuator/prometheus"
        - job_name: "server2"
          static_configs:
            - targets: ["server2:8082"]
          metrics_path: "/actuator/prometheus"
        - job_name: "server3"
          static_configs:
            - targets: [ "server3:8083" ]
          metrics_path: "/actuator/prometheus"
          

processors:
  batch:

exporters:
  prometheusremotewrite:
    endpoint: http://prometheus:9090/api/v1/write
    tls:
      insecure: true
  otlphttp/traces:
    endpoint: http://tempo:4318
    tls:
      insecure: true
  otlphttp/logs:
    endpoint: http://loki:3100/otlp
    tls:
      insecure: true
  debug/metrics:
    verbosity: detailed
  debug/traces:
    verbosity: detailed
  debug/logs:
    verbosity: detailed

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/traces]
    metrics:
      receivers: [otlp, prometheus/collector]
      processors: [batch]
      exporters: [prometheusremotewrite]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/logs]
